# coding: utf-8

"""
    Layered Control

    LI Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_runtime_api
from layint_runtime_api.rest import ApiException
from layint_runtime_api.models.container_logs import ContainerLogs


class TestContainerLogs(unittest.TestCase):
    """ ContainerLogs unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerLogs(self):
        """
        Test ContainerLogs
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = layint_runtime_api.models.container_logs.ContainerLogs()
        pass


if __name__ == '__main__':
    unittest.main()
