# coding: utf-8

"""
    Layered Control

    LI Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_runtime_api
from layint_runtime_api.rest import ApiException
from layint_runtime_api.apis.image_api import ImageApi


class TestImageApi(unittest.TestCase):
    """ ImageApi unit test stubs """

    def setUp(self):
        self.api = layint_runtime_api.apis.image_api.ImageApi()

    def tearDown(self):
        pass

    def test_add_image(self):
        """
        Test case for add_image

        Create new image definition
        """
        pass

    def test_assign_configuration_to_image(self):
        """
        Test case for assign_configuration_to_image

        Assign configuration to image
        """
        pass

    def test_assign_policy_to_image(self):
        """
        Test case for assign_policy_to_image

        Assign security policy to image
        """
        pass

    def test_delete_image(self):
        """
        Test case for delete_image

        Delete specified image
        """
        pass

    def test_get_image(self):
        """
        Test case for get_image

        Get specified container image
        """
        pass

    def test_get_images(self):
        """
        Test case for get_images

        Get defined container images
        """
        pass

    def test_instrument_image(self):
        """
        Test case for instrument_image

        Request instrumentation of specified container image
        """
        pass

    def test_number_of_instrumented_images(self):
        """
        Test case for number_of_instrumented_images

        Returns number of instrumented images
        """
        pass

    def test_show_container_running_image(self):
        """
        Test case for show_container_running_image

        Get specified container image
        """
        pass

    def test_update_image(self):
        """
        Test case for update_image

        Update image definition
        """
        pass


if __name__ == '__main__':
    unittest.main()
