# coding: utf-8

"""
    Layered Control

    LI Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_runtime_api
from layint_runtime_api.rest import ApiException
from layint_runtime_api.apis.event_api import EventApi


class TestEventApi(unittest.TestCase):
    """ EventApi unit test stubs """

    def setUp(self):
        self.api = layint_runtime_api.apis.event_api.EventApi()

    def tearDown(self):
        pass

    def test_describe_event(self):
        """
        Test case for describe_event

        Gets description about specific event
        """
        pass


if __name__ == '__main__':
    unittest.main()
