# coding: utf-8

"""
    Layered Control

    LI Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_runtime_api
from layint_runtime_api.rest import ApiException
from layint_runtime_api.apis.container_api import ContainerApi


class TestContainerApi(unittest.TestCase):
    """ ContainerApi unit test stubs """

    def setUp(self):
        self.api = layint_runtime_api.apis.container_api.ContainerApi()

    def tearDown(self):
        pass

    def test_build_container_dossier_tempate(self):
        """
        Test case for build_container_dossier_tempate

        Builds a security policy based on containers behavior
        """
        pass

    def test_get_container_dossier(self):
        """
        Test case for get_container_dossier

        Gets dossier for container
        """
        pass

    def test_get_container_logs(self):
        """
        Test case for get_container_logs

        Gets behavioral logs for container
        """
        pass

    def test_get_containers(self):
        """
        Test case for get_containers

        Get containers
        """
        pass

    def test_toggle_container_sniffer(self):
        """
        Test case for toggle_container_sniffer

        Toggles network sniffer
        """
        pass


if __name__ == '__main__':
    unittest.main()
